name: Continuous Integration
on: [push]
jobs:
  call-continuous-integration-reusable:
    uses: srikanth-123git/github-reusable-workflows/.github/workflows/ci.yml@main
    with:
      project_name: expense-backend
    secrets: inherit


