name: Release
on:
  push:
    tags:
      - "*"
jobs:
  call-release-reusable:
    uses: srikanth-123git/github-reusable-workflows/.github/workflows/release.yml@main
    with:
      project_name: expense-backend
      npm_install: true
      release_archive_file: "*.js package.json schema VERSION node_modules"
    secrets: inherit
